# Generated by Django 3.2.13 on 2022-11-23 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_num', models.IntegerField()),
                ('backdrop_path', models.TextField(blank=True, null=True)),
                ('production_countries', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_num', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_num', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('released_date', models.DateTimeField()),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_avg', models.FloatField()),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('click_count', models.IntegerField(null=True)),
                ('click_users', models.ManyToManyField(related_name='click_movies', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
