# Generated by Django 3.2.13 on 2022-11-21 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_movie_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='click_users',
            field=models.ManyToManyField(related_name='click_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
